/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#eae8e7",
        "primary-fixed-dim": "#ffb4a3",
        "on-primary-container": "#120100",
        "secondary-fixed-dim": "#b0cdbb",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-secondary-container": "#4f6a5b",
        "tertiary-fixed-dim": "#c6c7c2",
        "background": "#fbf9f8",
        "on-tertiary-fixed": "#1a1c19",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#ffb4a3",
        "on-secondary-fixed-variant": "#324c3e",
        "primary-container": "#c0573e",
        "on-tertiary": "#ffffff",
        "on-background": "#1b1c1c",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#812914",
        "inverse-surface": "#303030",
        "surface-bright": "#fbf9f8",
        "inverse-on-surface": "#f3f0f0",
        "surface": "#fbf9f8",
        "on-secondary-fixed": "#062014",
        "secondary-fixed": "#ccead6",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#496455",
        "tertiary-container": "#767773",
        "surface-tint": "#a03f29",
        "tertiary-fixed": "#e3e3de",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2e1",
        "on-error-container": "#93000a",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#3d0700",
        "primary": "#a03f28",
        "error": "#ba1a1a",
        "outline-variant": "#ddc0ba",
        "surface-container-highest": "#e4e2e1",
        "on-tertiary-fixed-variant": "#454744",
        "surface-dim": "#dcd9d9",
        "primary-fixed": "#ffdad2",
        "outline": "#8a726c",
        "on-surface-variant": "#56423d",
        "secondary-container": "#ccead6",
        "on-surface": "#1b1c1c",
        "tertiary": "#5d5e5b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "card": "24px"
      },
      spacing: {
        "stack-sm": "12px",
        "stack-lg": "48px",
        "base": "8px",
        "margin-mobile": "16px",
        "stack-md": "24px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"]
      },
    },
  },
  plugins: [],
}